// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AppleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void apple() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1074, 672));
    driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("q")).sendKeys("amazon phone");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".g:nth-child(4) .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".g:nth-child(4) .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_c3Rvc_gridColumn_2Jfab:nth-child(1) .\\_c3Rvc_image_1pfbQ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_c3Rvc_gridColumn_2Jfab:nth-child(1) .\\_c3Rvc_image_1pfbQ")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_c3Rvc_gridColumn_2Jfab:nth-child(1) .\\_c3Rvc_image_1pfbQ"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    js.executeScript("window.scrollTo(0,542)");
    js.executeScript("window.scrollTo(0,1126.6666259765625)");
    driver.findElement(By.cssSelector("#qiq3v7ynbh .style__overlay__2qYgu")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#qiq3v7ynbh .style__overlay__2qYgu"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.close();
  }
}
