// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OneplusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void oneplus() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1074, 672));
    driver.findElement(By.name("q")).sendKeys("ama");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("b > i")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    js.executeScript("window.scrollTo(0,490.6666564941406)");
    driver.findElement(By.cssSelector("#K_KId92UZ42S2iWLFwoYTA .a-section:nth-child(1) > .a-section:nth-child(2) .landscape-image")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#K_KId92UZ42S2iWLFwoYTA .a-section:nth-child(1) > .a-section:nth-child(2) .landscape-image"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ShovelerList-module__deal_1nfuKGTIIiECCZAYmsOMuP:nth-child(2) img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ShovelerList-module__deal_1nfuKGTIIiECCZAYmsOMuP:nth-child(2) img"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.close();
  }
}
